'use strict';

const ERR_CODE_NO_SUCH_FILE = 'ENOENT';
const ERRNO_NO_SUCH_FILE = -4058;
const SIGNALS_FOR_PROCESSING = ['SIGHUP', 'SIGINT', 'SIGQUIT', 'SIGTERM'];

module.exports = {
  ERRNO_NO_SUCH_FILE,
  ERR_CODE_NO_SUCH_FILE,
  SIGNALS_FOR_PROCESSING,
};
